### ISSUE TITLE
Different Axis models not compatible

### ISSUE THREAD

**Issue by OSCARPNNL** [Botts-Innovative-Research/osh-oakridge-buildnode#10]
We have discovered while trying to connect various Axis model cameras that not all connect. We were able to successfully connect and stream data from Axis P1467-LE Bullet Camera but not a AXIS P1455-LE Network Camera with the same syntax or any modified syntax we tried. What syntax is needed to communicate with all Axis cameras, and can this difference in model be investigated?

**Comment by tyronechrisharris** [comment]
I think there are at least two issues. 
1. Once the axis driver has been connected in the mjpeg configuration, the system will continue to view the device as mjpeg even if you switch to h264. So I started with a clean instance.
2. The axis driver is failing to connect to the camera with the username and password. I can connect to the camera without a user name and password if I allow anonymous viewers on the camera.
Here is the error log. I have a video of the setup.


2024-12-19 22:23:11.477 ERROR [ModuleRegistry-10] - Cannot initialize module 
org.sensorhub.api.client.ClientException: Error connecting to remote endpoint
	at NativeClassLoader//org.sensorhub.impl.module.RobustConnection.waitForConnection(RobustConnection.java:100)
	at NativeClassLoader//org.sensorhub.impl.sensor.axis.AxisCameraDriver.doInit(AxisCameraDriver.java:195)
	at NativeClassLoader//org.sensorhub.impl.module.AbstractModule.init(AbstractModule.java:401)
	at NativeClassLoader//org.sensorhub.impl.module.AbstractModule.updateConfig(AbstractModule.java:148)
	at NativeClassLoader//org.sensorhub.impl.sensor.AbstractSensorModule.updateConfig(AbstractSensorModule.java:762)
	at NativeClassLoader//org.sensorhub.impl.sensor.AbstractSensorModule.updateConfig(AbstractSensorModule.java:91)
	at NativeClassLoader//org.sensorhub.impl.module.ModuleRegistry.lambda$updateModuleConfigAsync$4(ModuleRegistry.java:844)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: Received HTTP error code 401
	at NativeClassLoader//org.sensorhub.impl.comm.RobustHTTPConnection.tryConnectHTTP(RobustHTTPConnection.java:89)
	at NativeClassLoader//org.sensorhub.impl.comm.RobustHTTPConnection.tryConnectGET(RobustHTTPConnection.java:103)
	at NativeClassLoader//org.sensorhub.impl.sensor.axis.AxisCameraDriver$1.tryConnect(AxisCameraDriver.java:116)
	at NativeClassLoader//org.sensorhub.impl.module.RobustConnection.waitForConnection(RobustConnection.java:96)
	... 11 common frames omitted
2024-12-19 22:28:03.304 ERROR [ModuleRegistry-13] - Error while disconnecting from RTSP server
java.io.IOException: RTSP Server Error: RTSP/1.0 401 Unauthorized
	at NativeClassLoader//org.sensorhub.impl.sensor.rtpcam.RTSPClient.parseResponse(RTSPClient.java:321)
	at NativeClassLoader//org.sensorhub.impl.sensor.rtpcam.RTSPClient.sendRequestAndParseResponse(RTSPClient.java:173)
	at NativeClassLoader//org.sensorhub.impl.sensor.rtpcam.RTSPClient.teardown(RTSPClient.java:153)
	at NativeClassLoader//org.sensorhub.impl.sensor.rtpcam.RTPVideoOutput.stop(RTPVideoOutput.java:226)
	at NativeClassLoader//org.sensorhub.impl.sensor.axis.AxisCameraDriver.doStop(AxisCameraDriver.java:347)
	at NativeClassLoader//org.sensorhub.impl.module.AbstractModule.stop(AbstractModule.java:569)
	at NativeClassLoader//org.sensorhub.impl.sensor.SensorSystem.doStop(SensorSystem.java:233)
	at NativeClassLoader//org.sensorhub.impl.module.AbstractModule.stop(AbstractModule.java:569)
	at NativeClassLoader//org.sensorhub.impl.module.ModuleRegistry.lambda$stopModuleAsync$2(ModuleRegistry.java:752)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-19 22:28:42.700 ERROR [ModuleRegistry-14] - Cannot initialize module 
org.sensorhub.api.client.ClientException: Error connecting to remote endpoint
	at NativeClassLoader//org.sensorhub.impl.module.RobustConnection.waitForConnection(RobustConnection.java:100)
	at NativeClassLoader//org.sensorhub.impl.sensor.axis.AxisCameraDriver.doInit(AxisCameraDriver.java:195)
	at NativeClassLoader//org.sensorhub.impl.module.AbstractModule.init(AbstractModule.java:401)
	at NativeClassLoader//org.sensorhub.impl.module.AbstractModule.updateConfig(AbstractModule.java:148)
	at NativeClassLoader//org.sensorhub.impl.sensor.AbstractSensorModule.updateConfig(AbstractSensorModule.java:762)
	at NativeClassLoader//org.sensorhub.impl.sensor.AbstractSensorModule.updateConfig(AbstractSensorModule.java:91)
	at NativeClassLoader//org.sensorhub.impl.module.ModuleRegistry.lambda$updateModuleConfigAsync$4(ModuleRegistry.java:844)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: Received HTTP error code 401
	at NativeClassLoader//org.sensorhub.impl.comm.RobustHTTPConnection.tryConnectHTTP(RobustHTTPConnection.java:89)
	at NativeClassLoader//org.sensorhub.impl.comm.RobustHTTPConnection.tryConnectGET(RobustHTTPConnection.java:103)
	at NativeClassLoader//org.sensorhub.impl.sensor.axis.AxisCameraDriver$1.tryConnect(AxisCameraDriver.java:116)
	at NativeClassLoader//org.sensorhub.impl.module.RobustConnection.waitForConnection(RobustConnection.java:96)
	... 11 common frames omitted

**Comment by tyronechrisharris** [comment]
I retried connecting to the axis cameras without authentication and it did not work. I have attached relevant file. 
[Failed_axis_rtsp_anon.log](https://github.com/user-attachments/files/18353893/Failed_axis_rtsp_anon.log)
[moduledata.zip](https://github.com/user-attachments/files/18353907/moduledata.zip)
[config (2).json](https://github.com/user-attachments/files/18353908/config.2.json)

**Comment by OSCARPNNL** [comment]
This appears tied to using older versions of java (17 rather than 21), but should be considered if there is anything else contributing to this issue.

**Comment by tyronechrisharris** [comment]
The Java 21 change seemed to fix the problem with the 1455 camera not working with the mjpeg via http. The rtsp issue remains.
